# Generated by Django 3.0.3 on 2020-03-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watched_list',
            field=models.ManyToManyField(null=True, to='app.Movie'),
        ),
    ]
