# Generated by Django 3.0.3 on 2020-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_watched_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre_preference',
            field=models.ManyToManyField(null=True, to='app.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='watched_list',
            field=models.ManyToManyField(null=True, to='app.Movie'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
