# Generated by Django 3.0.3 on 2020-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200311_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='app.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre_preference',
            field=models.ManyToManyField(to='app.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watched_list',
            field=models.ManyToManyField(to='app.Movie'),
        ),
    ]
